### ISSUE TITLE
sysctl.conf explanation

### ISSUE THREAD

**Issue by trandrew** [jaketame/scripts#2]
When running upload-cloud.sh script, my active downloading torrents go from 10-20mb/sec to 0-10kb/sec. I'm on a 1gigabit up/down connection. Is this behavior part of sysctl.conf?

**Comment by jaketame** [comment]
When running upload cloud it's pushing all your data to your cloud provider (Amazon) thus its utilising the whole connection thus download speeds will reduce.

On 2 Mar 2017, at 22:07, Andrew Tran <notifications@github.com> wrote:

When running upload-cloud.sh script, my active downloading torrents go from 10-20mb/sec to 0-10kb/sec. I'm on a 1gigabit up/down connection. Is this behavior part of sysctl.conf?

**Comment by trandrew** [comment]
Okay sounds good. Does not copying the sysctl.conf file over break functionality with the scripts?

**Comment by jaketame** [comment]
No the scripts will work fine. Sysctl.conf is tuning to the OS that helps with throughput of network.

On 2 Mar 2017, at 22:12, Andrew Tran <notifications@github.com> wrote:

Okay sounds good. Does not copying the sysctl.conf file over break functionality with the scripts?
